name: Build and publish site
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: Rscript -e 'install.packages(c("rmarkdown","tinytex"), repos="https://cloud.r-project.org"); tinytex::install_tinytex()'

      - name: Render RMarkdown
        run: Rscript -e 'rmarkdown::render("docs/index.Rmd", output_dir = "docs")'

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: docs/EDPoblacionv1.0.tex

      - name: Move PDF to docs directory
        run: |
          if [ -f "EDPoblacionv1.0.pdf" ]; then mv EDPoblacionv1.0.pdf docs/EDPoblacionv1.0.pdf; fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs